image: "julia:1"

variables:
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"
  JULIA_NUM_THREADS: '4'
  
cache:
  paths:
    - .julia/

build:
  stage: build
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.update();
                          Pkg.instantiate();
                          using OrdinaryDiffEq;'
  only:
  - master
  - tags
  - external
  - pushes
  
test-Interface:
  stage: test
  variables:
    GROUP: "Interface"
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.test("OrdinaryDiffEq"; coverage=true);'
  only:
  - master
  - tags
  - external
  - pushes

test-Regression:
  stage: test
  variables:
    GROUP: "Regression"
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.test("OrdinaryDiffEq"; coverage=true);'
  only:
  - master
  - tags
  - external
  - pushes


test-Integrators:
  stage: test
  variables:
    GROUP: "Integrators"
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.test("OrdinaryDiffEq"; coverage=true);'
  only:
    - master
    - tags
    - external
    - pushes

test-AlgConvergence_I:
  stage: test
  variables:
    GROUP: "AlgConvergence_I"
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.test("OrdinaryDiffEq"; coverage=true);'
  only:
    - master
    - tags
    - external
    - pushes

test-AlgConvergence_II:
  stage: test
  variables:
    GROUP: "AlgConvergence_II"
    BAYES_N: 100
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.test("OrdinaryDiffEq"; coverage=true);'
  only:
    - master
    - tags
    - external
    - pushes


test-AlgConvergence_III:
  stage: test
  variables:
    GROUP: "AlgConvergence_III"
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.test("OrdinaryDiffEq"; coverage=true);'
  only:
  - master
  - tags
  - external
  - pushes
