image: "julia:1"

variables:
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"
  JULIA_NUM_THREADS: '8'
  
cache:
  paths:
    - .julia/

build:
  stage: build
  tags: 
    - 'diffeqbasic'
  script:
    - julia -e "using InteractiveUtils;
                versioninfo()"
    - julia --project -e "using Pkg;
                          Pkg.update();
                          Pkg.instantiate();
                          Pkg.build(\"OrdinaryDiffEq\");
                          pkg\"precompile\";
                          using OrdinaryDiffEq;"
  only:
  - master
  - tags
  - external
  - pushes
  
test-Interface:
  stage: test
  tags: 
    - 'diffeqbasic'
    - 'gitlab-org'
  variables:
    GROUP: "Interface"
  script:
    - julia -e "using InteractiveUtils;
                versioninfo()"
    - julia --project -e "using Pkg;
                          Pkg.test(\"OrdinaryDiffEq\"; coverage=true);"
  only:
  - master
  - tags
  - external
  - pushes

test-Regression:
  stage: test
  tags: 
    - 'diffeqfast'
  variables:
    GROUP: "Regression"
  script:
    - julia -e "using InteractiveUtils;
                versioninfo()"
    - julia --project -e "using Pkg;
                          Pkg.test(\"OrdinaryDiffEq\"; coverage=true);"
  only:
  - master
  - tags
  - external
  - pushes

test-Integrators:
  stage: test
  tags: 
    - 'diffeqbasic'
  variables:
    GROUP: "Integrators"
  script:
    - julia -e "using InteractiveUtils;
                versioninfo()"
    - julia --project -e "using Pkg;
                          Pkg.test(\"OrdinaryDiffEq\"; coverage=true);"
  only:
    - master
    - tags
    - external
    - pushes

test-AlgConvergence_I:
  stage: test
  tags: 
    - 'diffeqbasic'
  variables:
    GROUP: "AlgConvergence_I"
  script:
    - julia -e "using InteractiveUtils;
                versioninfo()"
    - julia --project -e "using Pkg;
                          Pkg.test(\"OrdinaryDiffEq\"; coverage=true);"
  only:
    - master
    - tags
    - external
    - pushes

test-AlgConvergence_II:
  stage: test
  tags: 
    - 'diffeqbasic'
  variables:
    GROUP: "AlgConvergence_II"
  script:
    - julia -e "using InteractiveUtils;
                versioninfo()"
    - julia --project -e "using Pkg;
                          Pkg.test(\"OrdinaryDiffEq\"; coverage=true);"
  only:
    - master
    - tags
    - external
    - pushes


test-AlgConvergence_III:
  stage: test
  tags: 
    - 'diffeqbasic'
  variables:
    GROUP: "AlgConvergence_III"
  script:
    - julia -e "using InteractiveUtils;
                versioninfo()"
    - julia --project -e "using Pkg;
                          Pkg.test(\"OrdinaryDiffEq\"; coverage=true);"
  only:
  - master
  - tags
  - external
  - pushes

coverage:
  stage: deploy
  tags: 
    - 'diffeqbasic'
  dependencies:
    - test-Interface
    - test-Regression
    - test-Integrators
    - test-AlgConvergence_I
    - test-AlgConvergence_II
    - test-AlgConvergence_III
  script:
    - julia --project -e "using Pkg;
                          Pkg.add(\"Coverage\")"
    - julia --project -e "using Coverage;
                          cl, tl = get_summary(process_folder());
                          println(\"(\", cl/tl*100, \"%) covered\");
                          Codecov.submit_local(process_folder(), ".")"
  coverage: '/\(\d+.\d+\%\) covered/'
